//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4thIR.OpenAI.ChatGPT.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4thIR.OpenAI.ChatGPT.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key..
        /// </summary>
        public static string GenerateCompletion_APIKey_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_APIKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string GenerateCompletion_APIKey_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_APIKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting completion..
        /// </summary>
        public static string GenerateCompletion_CompletionResult_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_CompletionResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Result.
        /// </summary>
        public static string GenerateCompletion_CompletionResult_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_CompletionResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates completions based on the prompt(s) provided. Supports: summarization, translation, grammar correction, question answering, chatbots, composing emails, etc..
        /// </summary>
        public static string GenerateCompletion_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Completion.
        /// </summary>
        public static string GenerateCompletion_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo back the prompt in addition to the completion..
        /// </summary>
        public static string GenerateCompletion_Echo_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_Echo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string GenerateCompletion_Echo_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_Echo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale of the penalty for how often a token is used..
        /// </summary>
        public static string GenerateCompletion_FrequencyPenalty_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_FrequencyPenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Penalty.
        /// </summary>
        public static string GenerateCompletion_FrequencyPenalty_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_FrequencyPenalty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the log probabilities on the most likely tokens..
        /// </summary>
        public static string GenerateCompletion_LogProbabilities_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_LogProbabilities_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Probabilities.
        /// </summary>
        public static string GenerateCompletion_LogProbabilities_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_LogProbabilities_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of tokens to generate..
        /// </summary>
        public static string GenerateCompletion_MaximumLength_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_MaximumLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length.
        /// </summary>
        public static string GenerateCompletion_MaximumLength_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_MaximumLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of tokens to generate..
        /// </summary>
        public static string GenerateCompletion_MaximumTokens_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_MaximumTokens_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Tokens.
        /// </summary>
        public static string GenerateCompletion_MaximumTokens_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_MaximumTokens_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model used to generate the completion..
        /// </summary>
        public static string GenerateCompletion_Model_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string GenerateCompletion_Model_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_Model_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many different choices to request for each prompt..
        /// </summary>
        public static string GenerateCompletion_NumberOfOutputs_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_NumberOfOutputs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Outputs.
        /// </summary>
        public static string GenerateCompletion_NumberOfOutputs_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_NumberOfOutputs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale of the penalty applied if a token is already present at all..
        /// </summary>
        public static string GenerateCompletion_PresencePenalty_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_PresencePenalty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence Penalty.
        /// </summary>
        public static string GenerateCompletion_PresencePenalty_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_PresencePenalty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prompts to be processed..
        /// </summary>
        public static string GenerateCompletion_Prompts_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_Prompts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompts.
        /// </summary>
        public static string GenerateCompletion_Prompts_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_Prompts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stop sequence where the API will stop generating further tokens. The returned text will not contain the stop sequence..
        /// </summary>
        public static string GenerateCompletion_StopSequences_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_StopSequences_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sequences.
        /// </summary>
        public static string GenerateCompletion_StopSequences_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_StopSequences_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls randomness. Lowering results in less random completions as the value approaches 0. (0-1).
        /// </summary>
        public static string GenerateCompletion_Temperature_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GenerateCompletion_Temperature_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_Temperature_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls diversity via nucleus sampling..
        /// </summary>
        public static string GenerateCompletion_TopP_Description {
            get {
                return ResourceManager.GetString("GenerateCompletion_TopP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top P.
        /// </summary>
        public static string GenerateCompletion_TopP_DisplayName {
            get {
                return ResourceManager.GetString("GenerateCompletion_TopP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
